---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 60m
  url: https://charts.jetstack.io

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 60m
  targetNamespace: cert-manager
  install:
    createNamespace: true
    crds: CreateReplace
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 60m
  values:
    namespace: cert-manager
    crds:
      enabled: true
    prometheus:
      servicemonitor:
        enabled: false
    dns01RecursiveNameservers: "1.1.1.1:53"
    dns01RecursiveNameserversOnly: true
