---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-components
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/flux-system/deploy
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
