---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 60m
  url: https://helm.cilium.io/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 60m
  targetNamespace: kube-system
  install:
    createNamespace: true
    crds: CreateReplace
  chart:
    spec:
      chart: cilium
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 60m
  values:
    cni:
      exclusive: false
    kubeProxyReplacement: true
    k8sServiceHost: "rke2.ny.eevee.bot"
    k8sServicePort: 6443
    routingMode: tunnel
    tunnelProtocol: geneve
    bpfClockProbe: true
    loadBalancer:
      mode: dsr
      dsrDispatch: geneve
    bpf:
      datapathMode: netkit
      masquerade: true
      preallocateMaps: true
      distributedLRU:
        enabled: true
      mapDynamicSizeRatio: 0.08
    pmtuDiscovery:
      enabled: true
    rollOutCiliumPods: true
    sctp:
      enabled: true
    hubble:
      enabled: false
      relay:
        enabled: false
    encryption:
      enabled: true
      type: wireguard
    socketLB:
      enabled: true
    externalIPs:
      enabled: true
    hostPort:
      enabled: true
    nodePort:
      enabled: true
    bgpControlPlane:
      enabled: true
    ipv4NativeRoutingCIDR: ""
    ipv6NativeRoutingCIDR: ""
    enableIPv4Masquerade: true
    enableIPv6Masquerade: true
    ipv4:
      enabled: true
    ipv6:
      enabled: true
    endpointRoutes:
      enabled: true
    envoy:
      enabled: false
    ipam:
      mode: multi-pool
      operator:
        autoCreateCiliumPodIPPools:
          default:
            ipv4:
              cidrs:
                - "172.16.0.0/16"
              maskSize: 24
            ipv6:
              cidrs:
                - "fd16:feed:f00d::/64"
              maskSize: 80

