---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 60m
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 60m
  install:
    createNamespace: true
    crds: CreateReplace
  chart:
    spec:
      chart: prometheus-operator-crds
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 60m
  values:
    crds:
      ## annotations add additional annotations to all CRDs
      annotations: {}

      ## alertmanagerconfigs configures the AlertManagerConfig CRD
      alertmanagerconfigs:
        ## enabled defines if the CRD should be installed
        enabled: true

      ## alertmanagers configures the AlertManager CRD
      alertmanagers:
        ## enabled defines if the CRD should be installed
        enabled: true

      ## podmonitors configures the PodMonitor CRD
      podmonitors:
        ## enabled defines if the CRD should be installed
        enabled: true

      ## probes configures the Probe CRD
      probes:
        ## enabled defines if the CRD should be installed
        enabled: true

      ## prometheusagents configures the PrometheusAgent CRD
      prometheusagents:
        ## enabled defines if the CRD should be installed
        enabled: true

      ## prometheuses configures the Prometheus CRD
      prometheuses:
        ## enabled defines if the CRD should be installed
        enabled: true

      ## prometheusrules configures the PrometheusRule CRD
      prometheusrules:
        ## enabled defines if the CRD should be installed
        enabled: true

      ## prometheusrules configures the PrometheusRule CRD
      scrapeconfigs:
        ## enabled defines if the CRD should be installed
        enabled: true

      ## servicemonitors configures the ServiceMonitor CRD
      servicemonitors:
        ## enabled defines if the CRD should be installed
        enabled: true

      ## thanosrulers configures the ThanosRuler CRD
      thanosrulers:
        ## enabled defines if the CRD should be installed
        enabled: true
