---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-k8s-monitoring
  namespace: flux-system
spec:
  interval: 60m
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 60m
  targetNamespace: monitoring
  install:
    createNamespace: true
    crds: CreateReplace
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana-k8s-monitoring
        namespace: flux-system
      interval: 60m
  values:
    cluster: # Cluster configuration, including the cluster name
      name: ny.eevee.bot

    destinations:
      - name: honkwatch-mimir
        type: prometheus
        url: https://mimir.honk.watch/api/v1/push
        tenantId: honkwatch
        secret:
          create: false
          name: honkwatch-credentials
          namespace: monitoring
        auth:
          type: basic

      - name: honkwatch-loki
        type: loki
        url: https://loki.honk.watch/loki/api/v1/push
        secret:
          create: false
          name: honkwatch-credentials
          namespace: monitoring
        auth:
          type: basic

      - name: honkwatch-tempo
        type: otlp
        url: https://tempo.example.com/api/v1/traces
        secret:
          create: false
          name: honkwatch-credentials
          namespace: monitoring
        auth:
          type: basic

    # Features to enable, which determines what data to collect
    clusterMetrics:
      enabled: true
    clusterEvents:
      enabled: true
    nodeLogs:
      enabled: true
    podLogs:
      enabled: true
    applicationObservability:
      enabled: true
      receivers:
        otlp:
          grpc:
            enabled: true
    annotationAutodiscovery:
      enabled: true
    prometheusOperatorObjects:
      enabled: true

    # Telemetry collector definitions
    alloy-metrics:
      enabled: true
    alloy-logs:
      enabled: true
    alloy-singleton:
      enabled: true
    alloy-receiver:
      enabled: true

    node-exporter:
      metricsTuning:
        useDefaultAllowList: true
        useIntegrationAllowList: true

