apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: eevee-bot-connector-discord-secrets
  namespace: eevee-bot
stringData:
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:qlR8NRBr+xONOXmg86tVhdAgRpHjnjIuOvUppK65DWwOKsxYdqYcrqMJufssuKjF+teEPSOq6p3KoBVmOU4AscUWG0Cs4+XX,iv:Ijz8q9ApoPk7MA3+xZvURIsD9zJFZPx/e33dQ0l2g6k=,tag:6fYXk9D06AUQmrA9X+5Pdg==,type:str]
sops:
  age:
    - recipient: age1cgrs4dhzusfgkqg5dcyepzpfttlf3cppjd3zuv0l4qju7cmq7fpsqltd7r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMmxqdm9Tc3BFTXVEcjhP
        M2NQVW90VWlLT1B2QTAza1hYbXgrczhRbFRFClRnWkwyVnJnMjg4TkhrbEdkUXov
        TC9OSlREci9oaDVUQmVONnBLbkd5cEUKLS0tIHg4RHB3U21uSGtWSjZCMVduWjI5
        RDhQTVdkY3QvV0U2dzFsdi9tUm1GNVEK/im0D9nO1LAuWPCybEOmLZbWhnWQgZiy
        0u2k2rDdIhZwc/v6IXgdLuZMFh6aeJ6Y1pIC3EXNVExC3rq8T/A4Iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T18:03:50Z"
  mac: ENC[AES256_GCM,data:HGFZIWzQW8kcoVKJzKSBTipPydbbjttUVNjWxs+jM+RYqCzl9C2E7mVi1UtIzdhuL8o5/HEaogK+/WVFqsAB5El6DnmXvoEm4xlNNsJSb1eZbW4maPSM9gwpG+jnOBi0Bzr6hCe29MeGryPVSb7GWBuPBsPHF1pzrmhVUiGxgb4=,iv:7Lzu61D/96zx+oUpa2aizNlbjkaFHlnEyb/wzboKVdQ=,tag:t/rYjIMM2+tDJfG7LAL4cw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
