---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eevee-eevee
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: eevee-bot
  install:
    createNamespace: true
    crds: CreateReplace
  dependsOn:
    - name: eevee-crds
      namespace: flux-system
  chart:
    spec:
      chart: eevee
      sourceRef:
        kind: HelmRepository
        name: eevee
        namespace: flux-system
      interval: 10m
  valuesFrom:
    - kind: Secret
      name: eevee-bot-operator-api-token
  values:
    # eevee Helm values

    # Values for operator chart
    operator:
      # Enable the operator chart
      enabled: true
    # Values for bot chart
    bot:
      # Name of this bot
      name: eevee-bot
      # IPC Configuration
      ipcConfig:
        # Name of the IPC config resource
        name: eevee-bot
        spec:
          # NATS configuration
          nats:
            # Managed NATS deployment configuration
            managed:
              # Should the eevee-operator deploy a NATS server for us?
              enabled: true
              # NATS container image to use
              image: docker.io/nats:latest
            # NATS token authentication configuration
            token:
              # Should the eevee-operator generate a token for NATS auth?
              generate: true
              # Secret reference
              secretKeyRef:
                secret:
                  name: nats-auth-secret
                key: token
      # Bot Modules
      botModules:
        - name: cli
          spec:
            # Number of cli instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/cli:1.2.15
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: true
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name - this identifies it as a cli
            moduleName: cli
        - name: router
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/router:2.4.6
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: true
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name - this identifies it as a router
            moduleName: router
            # Router configuration
            moduleConfig: |
              blocklist:
              - pattern: ".*"
                enabled: true
                description: "Ignore all from fishy-bot"
                platform: "irc"
                instance: "irc-wetfish-net"
                user: "fishy.*"
        - name: admin
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/admin:2.6.3
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: false
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name
            moduleName: admin
            mountOperatorApiToken: true
            moduleConfig: |
              admins:
              - displayName: "goos"
                # Unique identifier for this admin
                uuid: "0aeb8706-a7fa-4783-be4b-1856ac51af13"
                # Platforms this admin is accepted on (regex patterns)
                acceptedPlatforms:
                - "irc"
                # Authentication methods for this admin
                authentication:
                  # Currently supporting IRC hostmask identification
                  irc:
                    hostmask: "goos@Fish-tri.8c3.136.150.IP"
              - displayName: "goos|m"
              # Unique identifier for this admin
                uuid: "ef6766a1-e30c-4b62-b792-234884448042"
                # Platforms this admin is accepted on (regex patterns)
                acceptedPlatforms:
                - "irc"
                # Authentication methods for this admin
                authentication:
                  # Currently supporting IRC hostmask identification
                  irc:
                    hostmask: "weazzywetf@Fish-n6v.ee5.48.144.IP"
              ratelimits:
                join:
                  mode: drop
                  level: user
                  limit: 100
                  interval: 1m
                part:
                  mode: drop
                  level: user
                  limit: 100
                  interval: 1m
                showRatelimits:
                  mode: drop
                  level: user
                  limit: 100
                  interval: 1m
                moduleUptime:
                  mode: drop
                  level: user
                  limit: 100
                  interval: 1m
                moduleRestart:
                  mode: drop
                  level: user
                  limit: 100
                  interval: 1m
                showCommandRegistry:
                  mode: drop
                  level: user
                  limit: 100
                  interval: 1m
                listBotModules:
                  mode: drop
                  level: user
                  limit: 100
                  interval: 1m
        - name: echo
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/echo:1.3.3
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: false
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name
            moduleName: echo
            # Module config
            moduleConfig: |
              ratelimit:
                mode: drop
                level: user
                limit: 5
                interval: 1m
        - name: emote
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/emote:1.5.3
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: false
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name
            moduleName: emote
            # Module config
            moduleConfig: |
              ratelimit:
                mode: drop
                level: user
                limit: 10
                interval: 1m
        - name: seen
          spec:
            size: 1
            image: ghcr.io/eeveebot/seen:1.4.2
            pullPolicy: Always
            metrics: true
            metricsPort: 8080
            ipcConfig: eevee-bot
            moduleName: seen
            moduleConfig: |
              ratelimit:
                mode: drop
                level: user
                limit: 5
                interval: 1m
            # Persistent Volume Claim
            persistentVolumeClaim:
              storageClassName: filesystem
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: help
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/help:2.4.3
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: false
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name
            moduleName: help
            # Module config
            moduleConfig: |
              ratelimit:
                mode: drop
                level: user
                limit: 10
                interval: 1m
        - name: calculator
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/calculator:1.4.3
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: false
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name
            moduleName: calculator
            # Module config
            moduleConfig: |
              ratelimit:
                mode: drop
                level: user
                limit: 10
                interval: 1m
        - name: dice
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/dice:1.4.3
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: false
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name
            moduleName: dice
            # Module config
            moduleConfig: |
              ratelimit:
                mode: drop
                level: user
                limit: 10
                interval: 1m
        - name: superslap
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/superslap:1.6.2
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: false
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name
            moduleName: superslap
            # Module config
            moduleConfig: |
              ratelimit:
                mode: drop
                level: user
                limit: 10
                interval: 1m
              invulnerableUsers:
                hostmasks: []
                # - ".*@Fish-n6v.ee5.48.144.IP"
        - name: urltitle
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/urltitle:2.5.5
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: false
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name
            moduleName: urltitle
            # Module config
            moduleConfig: |
              ratelimit:
                mode: drop
                level: user
                limit: 5
                interval: 1m
            envSecret:
              name: eevee-bot-urltitle-secrets
        - name: weather
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/weather:1.4.2
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: false
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name
            moduleName: weather
            # Module config
            moduleConfig: |
              ratelimit:
                mode: drop
                level: user
                limit: 5
                interval: 1m
            envSecret:
              name: eevee-bot-weather-secrets
            # Persistent Volume Claim
            persistentVolumeClaim:
              storageClassName: filesystem
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: tell
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/tell:2.3.2
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: false
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name
            moduleName: tell
            # Module config
            moduleConfig: |
              ratelimit:
                mode: drop
                level: user
                limit: 5
                interval: 1m
            # Persistent Volume Claim
            persistentVolumeClaim:
              storageClassName: filesystem
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: connector-irc
          spec:
            # Number of module instances to deploy
            size: 1
            # Container image to use
            image: ghcr.io/eeveebot/connector-irc:1.5.12
            # Image pull policy
            pullPolicy: Always
            # Enable metrics
            metrics: true
            # Metrics port
            metricsPort: 8080
            # IPC configuration name
            ipcConfig: eevee-bot
            # Module name - this identifies it as an IRC connector
            moduleName: connector-irc
            # IRC configuration
            moduleConfig: |
              # List of IRC connections
              connections:
              # Display name for this network (no . or * or > allowed)
              - name: irc-wetfish-net

                # Enable this connection
                enabled: true

                # IRC connection configuration
                irc:
                  host: irc.wetfish.net
                  port: 6697
                  ssl: true
                  autoReconnect: true
                  autoReconnectWait: 5000
                  autoReconnectMaxRetries: 10
                  autoRejoin: true
                  autoRejoinWait: 5000
                  autoRejoinMaxRetries: 5
                  pingInterval: 30
                  pingTimeout: 120

                # IRC Ident information
                ident:
                  nick: eevee
                  username: eevee
                  gecos: eevee.bot
                  version: "0.4.20"
                  quitMsg: "eevee 0.4.20"

                # Actions to take after connecting
                postConnect:
                - # Join channels after connecting
                  action: join
                  join:
                  - channel: '#eevee'
                  - channel: '#botspam'
                  - channel: '#wetfish'

                # Send broadcast events for all received messages
                broadcastMessages: true
                # Settings related to command modules
                commands:
                  # Common prefix regex to add to registered command regexes
                  commonPrefixRegex: "^-"
# - name: connector-discord
#   spec:
#     # Number of module instances to deploy
#     size: 1
#     # Container image to use
#     image: ghcr.io/eeveebot/urltitle:2.5.5
#     # Image pull policy
#     pullPolicy: Always
#     # Enable metrics
#     metrics: false
#     # Metrics port
#     metricsPort: 8080
#     # IPC configuration name
#     ipcConfig: eevee-bot
#     # Module name
#     moduleName: connector-discord
#     # Module config
#     moduleConfig: |
#       ratelimit:
#         mode: drop
#         level: user
#         limit: 5
#         interval: 1m
#       connections:
#         - name: "eevee"
#           ident:
#             quitMsg: "eevee.bot shutting down"
#           discord:
#             intents:
#               - "GUILDS"
#               - "GUILD_MESSAGES"
#               - "MESSAGE_CONTENT"
#           postConnect: []
#     envSecret:
#       name: eevee-bot-connector-discord-secrets
