apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: eevee-bot-github-secrets
  namespace: eevee-bot
stringData:
  GITHUB_PAT: ENC[AES256_GCM,data:s0RizZczuGYuzykV/jP14NOl0C/8dtRc/51Z36BMLuyvNSX6r1/50N/o9NuG7wpS4xPTiLCs1/NPsv3Raow4w8sR+DOLIE5OyUg65A/NbmhqPBKtJKNbe7yf9IkC,iv:0wihhMvF1Og18oNF/cceEmSUZGFKHZH9rxPh+w2o7z8=,tag:xi2eWXbjOPnLWVer1XCbwg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdGo0MDdmWnBjdW80VnpS
        T2pqNTZoZGVZS1hpK1pSWkJBMUlwekNyV1d3CmlKSFU5RnFIMlgvYm1ENDBXS1Fv
        THFBWVQ2Qi9qd0tOMXI4amRMbDY3UmsKLS0tIEhyYWIveENSOUkrMHVNTXRDYytz
        YTZvRG5idXVTS1I2UUlNUW1QYlpQTE0Kl6NGUqaTAFFMKM5+lTmpP+C2EreJGFX9
        rFp2TjQVTeBy1/Z1BG3OAET8e71mIzJnj8TYUmfrO2m7hNzjkOceVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cgrs4dhzusfgkqg5dcyepzpfttlf3cppjd3zuv0l4qju7cmq7fpsqltd7r
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T00:32:38Z"
  mac: ENC[AES256_GCM,data:PAyqleIu8uc3vkiR7SNJzZ3IuPzUpscT9mYtFYa70dwmoVba9EsiK6T4YRN6KuixkULD0H2T69HNYw+sKMqUidNVZVB4az3QeY3tHf3jJ4rRgLHk8k6BsklwWI3pIEL8KCXAotubxh2aqSVYZTduXZlbeK3C8mnQlZT56lcibi8=,iv:aXP0QUJyys4kAFq0mZgCjhSo+SiNcUQOGvJxOrkEga8=,tag:em3c3ddjQpzQPMybkFmejQ==,type:str]
  version: 3.13.0
