---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepo.yaml
- crds.yaml
- eevee.yaml
- operator-api-token.sops.yaml
- weather-secrets.sops.yaml
- urltitle-secrets.sops.yaml
- eevee-bot-connector-discord-secrets.sops.yaml
- github-secrets.sops.yaml
