apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: eevee-bot-urltitle-secrets
  namespace: eevee-bot
stringData:
  YOUTUBE_API_KEY: ENC[AES256_GCM,data:ZMybjPT6XVCyY2MUXlTTnVulKamcB7JGhwQfJwyApwp2FAhy50qo,iv:UWZv7l9OutR4eTac65OAlaLx/AcB+3EH9Ru7Tu8sWTk=,tag:6QjaWHm9QS4C5XA4ZXL2Uw==,type:str]
sops:
  age:
    - recipient: age1cgrs4dhzusfgkqg5dcyepzpfttlf3cppjd3zuv0l4qju7cmq7fpsqltd7r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSWp4dTlwUnhVUXVZOFZT
        NXFvTGVRUHE3Ly8wdDcwUmxYQXQzZVZ1YXpvCmE3Q0docisxUWJxU08wcEIzOG5H
        clpKb2l6VXVuUDJ0TFdudUtlSXNIekEKLS0tIHNoMEhOVEdHUldDYVpBSlg0SEZr
        VHR3WUhncitxZm5TblBxdWwrcFFSVUEKY20G3KP9RQ1dmTOtJ54xQrn3KicIo/1a
        oDASEpr6OZrTPzfD9FCbwIjvL4i3IEJWtNR4L23GCYnGPePqW15UjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T07:54:06Z"
  mac: ENC[AES256_GCM,data:3xfQDo+XudUl0LWtT8w9HcRvw94h9Za557snFa/mL33Xc0BdxfNobAi0s0fLTC7f6T6F6Qof1q26IHZqPGBXVi1ndzFPTm5wWhvrDh2JxDaxdbyJXrrMNuxoZHKwI+AXp8J7FxKqo77lITnhAMflK/C7nwmfmwDS+nG+Bt2USsE=,iv:4mh8cRQaDAW7VX9GQ/LrB3owdiNmzLYq4l8a7l4nbvE=,tag:uYlRlkDCPwDVmqpyiJFlHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
