apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: eevee-bot-weather-secrets
  namespace: eevee-bot
stringData:
  PIRATE_WEATHER_API_KEY: ENC[AES256_GCM,data:FlyR7reB9suJhq2amX8iStIrXmv33RGV2jVTkBMa2Ys=,iv:iC9SZNX7nxeayU7uqrar5BodD/8Apk4Y25aPcYL19n4=,tag:IZAm7LsS2BFHNoqJnVcLVA==,type:str]
sops:
  age:
    - recipient: age1cgrs4dhzusfgkqg5dcyepzpfttlf3cppjd3zuv0l4qju7cmq7fpsqltd7r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNVBkcmlIMnJ1Y3pqSmtH
        Q2dBZWZLTjNvM1kvem5hbVZia3VPWUJCOWswCitkS2VLV2NnQlhKNGVueUVZZjBD
        dTRRRmRWY0YydVU2anpKZ2FnSG15RTQKLS0tIExmcE90RGpkV2NBYVlGU29mU0w1
        NWRKeVRXRnBDb2lOZk5yYWlSRURRcm8KRB8kIre0Ewfx65I3PbSf4dYsw7VVh+Xi
        5MgFqiWVK8RCpdsEAS9k4JNpGgM820LvOxbLlwRBQRDGvzu7ETMcvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T05:36:21Z"
  mac: ENC[AES256_GCM,data:v1BCNOApv+gC3NntKVVJ45MJs4E5TdZUMBkNUyZys+2GLACgjQ4MOkdiifNK82vXhoMeOnNaHInKFuAAB/yyQ7wach+7VOChHqhpWX82AewsT1oBvbUNZttuXJGCeLbI/zmBtYIhe0ee5h1u8EQT4OLYu0Oka15eqdhEHk8p6Bs=,iv:5N7RGHcnXK8gHNXBIPBKxc77oOaaULo1KeNcewl6WgM=,tag:YssMIpXLzlBCFePDSu/E8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
