---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 60m
  url: https://traefik.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 60m
  targetNamespace: traefik
  install:
    createNamespace: true
    crds: CreateReplace
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 60m
  values:
    deployment:
      enabled: true
      kind: Deployment
      replicas: 1
    logs:
      access:
        enabled: true
        format: common
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
        allowEmptyServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        allowEmptyServices: true
      file:
        enabled: true
        watch: true
        content: ""
    experimental:
      plugins: {}
    metrics:
      prometheus:
        service:
          enabled: false
        serviceMonitor:
          enabled: false
    ports:
      traefik:
        expose:
          default: false
      web:
        expose:
          default: true
        exposedPort: 80
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        expose:
          default: true
        exposedPort: 443
    service:
      enabled: true
      single: false
      type: LoadBalancer
      labels:
        ip-pool: eevee-lbip-001
      annotations:
        "lbipam.cilium.io/ips": "216.128.154.3,2001:19f0:5c00:14dc::100"
        "lbipam.cilium.io/sharing-key": "216.128.154.3,2001:19f0:5c00:14dc::100"
      ipFamilyPolicy: SingleStack
      ipFamilies:
      - IPv4
      - IPv6
