apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cilium-bgp-peer-secret
  namespace: kube-system
stringData:
  password: ENC[AES256_GCM,data:8mGkXOSVNAs/mfjsSCmZbw==,iv:Btgr6ARrSHSACr5BKOOXXjZItnE8+9IRYFoWwtbpalo=,tag:JFDdhvSe69OK6NZSRSdcPA==,type:str]
sops:
  age:
    - recipient: age1cgrs4dhzusfgkqg5dcyepzpfttlf3cppjd3zuv0l4qju7cmq7fpsqltd7r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVkdJR3lBR3gyMnFXVVdR
        NDlYZzlxWXd3ajdoUEFvL1RLYm9ZVjU4SldZCnFyOTBKRzRNQ1lHTXFpbEV1NVEx
        cFB4MXRlVldYeEVvWERlTEJrM250RzgKLS0tIDB4SmduVDZaVmFmY1V2SEpGU3A1
        SWNBSTQ0dGxkaTNLNjc3Z3EzUm1DSDQKGjcbTyZgol8uvegk0ns7GwhcrWE2Mk0d
        /9YQacnAozIOdFAaPzVvtNXbozIvONHLgLxaLIDgBuA/kdmJzlbgpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T03:36:20Z"
  mac: ENC[AES256_GCM,data:u6jRe+4UC6AcVGUjyhiZCAeK04267heKGXU6qWSWt7p17czttZOjHK/4Ap7mrj4KIa2RJifb8iorFWR6UUKQsidmYSySsRfiaqmSltlr78L9baHOunrjC94Jn1Ai9kOzC5jVOAi5NIxs/FIKKgQr4c3tbAXQbwCl125LY/vr4HE=,iv:nxNx9WT8xwh82riEmPLfiik/hkRJ7ATYtQ8Od0LJOUY=,tag:R3ouOkstgi0SvZCd51xBuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
