---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: vlan10
spec:
  serviceSelector:
    matchLabels:
      ip-pool: vlan10
  nodeSelector: {}
  interfaces:
  - enp6s18
  externalIPs: true
  loadBalancerIPs: true
